### ISSUE TITLE
versioning of the spec

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/decentralized-web-node#149]
Could we please give commit `1f82822` a version (v0.1 for example) and publish it on a DIF website? Microsoft is using this specification in production and we would like to be able to refer our clients, etc. to one document. We thought that the specification is relatively stable since very few changes have been made, but looks like some non-backward compatible changes are being made, so as a compromise would really appreciate if we can version a commit above. Thanks!

**Comment by csuwildcat** [comment]
Probably the best course for now is to 1) generate a PR that is a build of that commit, 2) has the new name and correct links to the latest version of the spec inserted wherever those are present in text, and then 3) post it in the readme as a previous iteration of the initial strawman version that has since been renamed and progressed from there. If a version is cut, it should probably reflect something like `0.0.1-predraft`. We can house the cut copy in the repo under spec/0.0.1-predraft.

**Comment by xinaxu** [comment]
@csuwildcat that's for taking a look into this. We need this to be ready in the next few weeks. Seems like you already have the plan in your mind but let me know if you need any effort on our side.

**Comment by andorsk** [comment]
Where did this leave off? Do we need to push a new effort here to address this issue?

**Comment by andorsk** [comment]
Discussed on DIF: 

Decide name for Milestone 1 and anchor on this for version spec.

**Comment by andorsk** [comment]
Initial version is v0.1.0. This is done. Proposing to close.
